#include <iostream>

using namespace std;

/* this is going to be all the functions we going to be using 
    to calculate the problem that the user has given us  */

void add(){

}

void subtract(){

}

void multiply(){

}

void divid(){

}

void remainder(){

}

void power(){

}

/* In the main fuction we are asking the user to give us the values and what operation 
    we going to be doing for the problems. */

int main(){

    int i, n;
    char op;
    cout << "Please enter your equation: ";
    cin >> i >> op >> n;


    return 0;
}